name: Plan / Test On PR

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@20ce4e5 #v1 gives a cred error
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive ./terraform


